[feat] #58 코드 실행 메서드 구현 확인
Error: Could not find or load main class main
Caused by: java.lang.ClassNotFoundException: main

해결을 위해 file 이름 Main.java 로 변경