[feat] #58 코드 실행 메서드 구현 확인
Error: Could not find or load main class main
Caused by: java.lang.ClassNotFoundException: main

경로에 문제가 있어서 작업디렉토리 설정